global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'hyperledger_metrics'
    scrape_interval: 10s
    static_configs:
      - targets: [
        'peer0.deoni.de:9443',
        'peer0.salers.de:9443',
        'peer0.brangus.de:9443',
        'peer0.pinzgauer.de:9443',
        'peer0.tuxer.de:9443',
        'peer0.authority.de:9443',
        'peer0.schwarzfuss.de:9443',
        'peer0.duroc.de:9443',
        'orderer.unibw.de:9443',
        'orderer1.unibw.de:9443',
        'orderer2.unibw.de:9443'
        ]
