# This work is licensed under a Creative Commons Attribution 4.0 International License
# (http://creativecommons.org/licenses/by/4.0/).
#
# Author(s): Tim Reimers, Andreas Hermann
# NutriSafe Research Project
# Institute for Protection and Dependability
# Department of Computer Science
# Bundeswehr University Munich
#
# Original file (from https://github.com/hyperledger/fabric-samples) by IBM Corp:
# License SPDX-License-Identifier: Apache-2.0

version: "2"

networks:
  orderingservice_basic:
    external: true

services:


#############################################Deoni########################################################

  restapi.nuttrisafe:
    container_name: restapi.nuttrisafe
    image: tatse/restapi
    working_dir: /host/var/run/
    ports:
      - 8080:8080
    volumes:
      - /var/run/:/host/var/run/
      - ../creatingCryptoMaterial/crypto-config/peerOrganizations/deoni.de/users/User1@deoni.de/msp:src/main/resources/credentials/User1@deoni.de/
    networks:
      - orderingservice_basic

 
