---
# This playbook deploys a simple peer organization.
- name: Create docker-compose file for organization
  hosts: all
  become: true
  vars: 
    pjroot: "{{ playbook_dir }}"
    orgdomain: "org.de"
  tasks: 
  - name: Install python dependencies
    apt: 
      force_apt_get: yes 
      name: 
        - python3
        - python3-setuptools
        - python3-pip
  - name: Install docker dependency for python
    pip: 
      name:
        - docker-py
  - name: Start peer
    community.docker.docker_container:
      name: peer0.{{orgdomain}}
      image: hyperledger/fabric-peer:2.2.1
      state: 'started'
      env:
        CORE_VM_ENDPOINT: 'unix:///host/var/run/docker.sock'
        CORE_PEER_ID: 'peer0.{{orgdomain}}'
        FABRIC_LOGGING_SPEC: 'info'
        CORE_CHAINCODE_LOGGING_LEVEL: 'info'
        CORE_PEER_LOCALMSPID: 'AuthorityMSP'
        CORE_PEER_MSPCONFIGPATH: '/etc/hyperledger/msp/peer/msp/'
        CORE_PEER_ADDRESS: 'peer0.{{orgdomain}}:7051'
        CORE_PEER_GOSSIP_ENDPOINT: 'peer0.{{orgdomain}}:7051'
        CORE_PEER_GOSSIP_BOOTSTRAP: '[peer0.deoni.de:7051 peer0.salers.de:7051 peer0.brangus.de:7051 peer0.tuxer.de:7051]'
        CORE_PEER_GOSSIP_EXTERNALENDPOINT: 'peer0.{{orgdomain}}:7051'
        CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: 'orderingservice_basic'
        CORE_LEDGER_STATE_STATEDATABASE: 'CouchDB'
        CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: 'couchdb.{{orgdomain}}:5984'
        CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: ''
        CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: ''
        CORE_PEER_TLS_ENABLED: 'true'
        CORE_PEER_TLS_CERT_FILE: '/etc/hyperledger/msp/peer/tls/server.crt'
        CORE_PEER_TLS_KEY_FILE: '/etc/hyperledger/msp/peer/tls/server.key'
        CORE_PEER_TLS_ROOTCERT_FILE: '/etc/hyperledger/msp/peer/tls/ca.crt'
        ORDERER_CA: '/etc/hyperledger/msp/peer/tls/tlsca.unibw.de-cert.pem'
        CORE_OPERATIONS_LISTENADDRESS: '0.0.0.0:9443'
        CORE_METRICS_PROVIDER: 'prometheus'