all:
    children:
        prod:
            vars:
                #Change these to match your environment BEFORE starting the playbook
                github_account:
                vm_ssh_user: <<INSERT USERNAME HERE>>              
            hosts:
                testvm-ubuntu20:
                    ansible_connection: ssh
                    ansible_host: 127.0.0.1
                    ansible_user: "{{ vm_ssh_user }}"
                    ansible_port: 2222